In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

rand_data= np.random.randint(low=-5,high=200, size=(10,4))
rand_df = pd.DataFrame(rand_data, columns=['col1', 'col2', 'col3', 'col4'])
print(rand_data)
print(rand_df)
print(rand_df)



[[ 52 191  35 149]
 [ 49  66  68  33]
 [ 77  57  93 150]
 [144  81 163 133]
 [ 93  72 176  45]
 [ 29 104  68  81]
 [157 152   9  97]
 [143 184 123 158]
 [187  84  96  11]
 [189  62  27  99]]
   col1  col2  col3  col4
0    52   191    35   149
1    49    66    68    33
2    77    57    93   150
3   144    81   163   133
4    93    72   176    45
5    29   104    68    81
6   157   152     9    97
7   143   184   123   158
8   187    84    96    11
9   189    62    27    99
   col1  col2  col3  col4
0    52   191    35   149
1    49    66    68    33
2    77    57    93   150
3   144    81   163   133
4    93    72   176    45
5    29   104    68    81
6   157   152     9    97
7   143   184   123   158
8   187    84    96    11
9   189    62    27    99


In [3]:
rand_df

col1  col2  col3  col4
0    52   191    35   149
1    49    66    68    33
2    77    57    93   150
3   144    81   163   133
4    93    72   176    45
5    29   104    68    81
6   157   152     9    97
7   143   184   123   158
8   187    84    96    11
9   189    62    27    99

In [4]:
rand_df.col1[5:]

5     29
6    157
7    143
8    187
9    189
Name: col1, dtype: int32

In [7]:
rand_df/rand_df.shift(1)-1


col1      col2       col3      col4
0       NaN       NaN        NaN       NaN
1 -0.057692 -0.654450   0.942857 -0.778523
2  0.571429 -0.136364   0.367647  3.545455
3  0.870130  0.421053   0.752688 -0.113333
4 -0.354167 -0.111111   0.079755 -0.661654
5 -0.688172  0.444444  -0.613636  0.800000
6  4.413793  0.461538  -0.867647  0.197531
7 -0.089172  0.210526  12.666667  0.628866
8  0.307692 -0.543478  -0.219512 -0.930380
9  0.010695 -0.261905  -0.718750  8.000000

In [23]:
import pathlib
TITANIC_DATAFILE = pathlib.Path("..","data", "titanic.csv")
pd.read_csv(TITANIC_DATAFILE)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]